- name: Upgrade all yum packages
  yum: name=* state=latest

- name: Install new yum packages
  yum: name={{ item }} state=installed
  with_items:
      # Useful
      - bind-utils
      - wget
      - screen
      - cronolog
      - java-1.7.0-openjdk-devel
      - httpd
      # Database
      - mysql
      - mysql-server
      - mysql-devel
      - MySQL-python  # Required for
      - libselinux-python
      - libsemanage-python
      # Python Dev
      - python-devel
      # Node.js
      - nodejs   # For Bootstrap
      - npm      # For Bootstrap
      # Misc
      - ImageMagick
      - zlib-devel

# Install Subversion 1.8
- name: Bootstrap WANdisco install
  copy: src=WANdisco-1.8.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: Fetch WANdisco RPM-GPG-KEY
  action: command wget http://opensource.wandisco.com/RPM-GPG-KEY-WANdisco -O /tmp/RPM-GPG-KEY-WANdisco

- name: Import WANdisco RPM-GPG-KEY
  action: command rpm --import /tmp/RPM-GPG-KEY-WANdisco
  
- name: Remove WANdisco RPM-GPG-KEY
  action: command rm -rf /tmp/RPM-GPG-KEY-WANdisco

- name: Install latest version of Subversion
  yum: name=subversion state=latest

# Copy and set IPTables rules
- name: Set iptables to autostart on boot
  action: command /sbin/chkconfig --level 345 iptables on
 
- name: Copy IPTables bash script
  copy: src=iptables.sh dest=/tmp/iptables.sh
  
- name: Run IPTables bash script
  action: command /bin/bash /tmp/iptables.sh

# Apache http setup and configuration
- name: Write the apache config file
  template: src=vhost.cnf.j2 dest=/etc/httpd/conf.d/{{ httpd_hostname }}.conf
  notify:
  - restart httpd

- name: Start Apache httpd
  service: name=httpd state=started enabled=true

- name: Ensure Apache httpd is running automatically at boot time
  action: command /sbin/chkconfig --level 345 httpd on

# MySQL setup and configuration
- name: Create MySQL configuration file
  template: src=mysql.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start MySQL Service
  service: name=mysqld state=started enabled=true

- name: Ensure MySQL is running automatically at boot time
  action: command /sbin/chkconfig --level 345 mysqld on

- name: Create Application Database
  mysql_db: name={{ db_name }} state=present

- name: Create Application DB User
  mysql_user: name={{ db_user }} password={{ db_password }} priv=*.*:ALL state=present
